export const REMOVE_ITEM = 'REMOVE_ITEM'
export const CLEAR_CART = 'CLEAR_CART'
export const RESET_CART = 'RESET_CART'
export const LOADING = 'LOADING'
export const CART_TOTAL = 'CART_TOTAL'
export const DISPLAY_ITEMS = 'DISPLAY_ITEMS'
export const TOGGLE_AMOUNT = 'TOGGLE_AMOUNT'
